"""Mocking a database for menu items and remaining quantities."""
import json
from room_service.models.menu import MenuItem

MENU_ITEMS: dict[str, MenuItem] = {
  # Mains
  "Club Sandwich": MenuItem(
    name="Club Sandwich",
    price=15.00,
    category="Main",
    modifications_allowed=True,
    description="Triple-decker sandwich with turkey, crispy bacon, lettuce, tomato, and mayonnaise",
    available_modifications=[
      "extra bacon",
      "no bacon",
      "toasted",
      "untoasted",
      "no tomato",
      "extra mayo",
    ],
    allergens=["gluten", "eggs", "dairy"],
    preparation_time=15,
    available_quantity=10,
  ),
  "Caesar Salad": MenuItem(
    name="Caesar Salad",
    price=12.00,
    category="Main",
    modifications_allowed=True,
    description="Crisp romaine lettuce, parmesan cheese, croutons, and classic Caesar dressing",
    available_modifications=[
      "add chicken",
      "no croutons",
      "dressing on side",
      "add anchovies",
    ],
    allergens=["gluten", "eggs", "dairy", "fish"],
    preparation_time=10,
    available_quantity=10,
  ),
  "Margherita Pizza": MenuItem(
    name="Margherita Pizza",
    price=16.00,
    category="Main",
    modifications_allowed=True,
    description="Fresh mozzarella, tomato sauce, and basil on our house-made crust",
    available_modifications=[
      "extra cheese",
      "well done",
      "gluten-free crust",
      "add pepperoni",
    ],
    allergens=["gluten", "dairy"],
    preparation_time=20,
    available_quantity=10,
  ),
  "Beef Burger": MenuItem(
    name="Beef Burger",
    price=18.00,
    category="Main",
    modifications_allowed=True,
    description="8oz Angus beef patty with lettuce, tomato, onion, and special sauce",
    available_modifications=[
      "add cheese",
      "no onion",
      "well done",
      "medium rare",
      "add bacon",
    ],
    allergens=["gluten", "eggs", "dairy"],
    preparation_time=18,
    available_quantity=10,
  ),
  # Beverages
  "Still Water": MenuItem(
    name="Still Water",
    price=4.00,
    category="Beverage",
    modifications_allowed=False,
    description="500ml bottle of premium spring water",
    available_modifications=[],
    allergens=[],
    preparation_time=2,
    available_quantity=10,
  ),
  "Sparkling Water": MenuItem(
    name="Sparkling Water",
    price=4.00,
    category="Beverage",
    modifications_allowed=False,
    description="500ml bottle of premium sparkling mineral water",
    available_modifications=[],
    allergens=[],
    preparation_time=2,
    available_quantity=10,
  ),
  "Fresh Orange Juice": MenuItem(
    name="Fresh Orange Juice",
    price=6.00,
    category="Beverage",
    modifications_allowed=True,
    description="Freshly squeezed orange juice",
    available_modifications=["no pulp", "extra pulp"],
    allergens=[],
    preparation_time=5,
    available_quantity=0,
  ),
  "House Red Wine": MenuItem(
    name="House Red Wine",
    price=12.00,
    category="Beverage",
    modifications_allowed=False,
    description="Glass of house Cabernet Sauvignon",
    available_modifications=[],
    allergens=["sulfites"],
    preparation_time=3,
    available_quantity=10,
  ),
  # Desserts
  "Apple Pie": MenuItem(
    name="Apple Pie",
    price=8.00,
    category="Dessert",
    modifications_allowed=True,
    description="Warm apple pie with cinnamon and buttery crust",
    available_modifications=["add ice cream", "heated", "not heated"],
    allergens=["gluten", "dairy"],
    preparation_time=8,
    available_quantity=10,
  ),
  "Chocolate Mousse": MenuItem(
    name="Chocolate Mousse",
    price=9.00,
    category="Dessert",
    modifications_allowed=True,
    description="Rich dark chocolate mousse with fresh whipped cream",
    available_modifications=[
      "extra whipped cream",
      "no whipped cream",
      "add berries",
    ],
    allergens=["dairy", "eggs"],
    preparation_time=5,
    available_quantity=0,
  ),
  "Fresh Fruit Plate": MenuItem(
    name="Fresh Fruit Plate",
    price=7.00,
    category="Dessert",
    modifications_allowed=True,
    description="Selection of seasonal fresh fruits",
    available_modifications=["no melons", "extra berries"],
    allergens=[],
    preparation_time=7,
    available_quantity=0,
  ),
  # Sides
  "French Fries": MenuItem(
    name="French Fries",
    price=6.00,
    category="Side",
    modifications_allowed=True,
    description="Crispy golden fries with sea salt",
    available_modifications=["extra crispy", "add truffle oil", "add parmesan"],
    allergens=[],
    preparation_time=10,
    available_quantity=5,
  ),
  "Garden Salad": MenuItem(
    name="Garden Salad",
    price=7.00,
    category="Side",
    modifications_allowed=True,
    description="Mixed greens, cucumber, tomato with house vinaigrette",
    available_modifications=["no tomato", "dressing on side", "add avocado"],
    allergens=[],
    preparation_time=5,
    available_quantity=0,
  ),
}

MENU_ITEMS_STRING = json.dumps({key: item.model_dump_json() for key, item in MENU_ITEMS.items()})